### ISSUE TITLE
Video upload

### ISSUE THREAD

**Issue by fokosun** [jrm2k6/cloudder#10]
This is not an issue per say. I was just wondering how video upload would be implemented, it was not mentioned in the README. In my application, i had two file uploaders, one for image upload and the other for video upload. Whenever i try to do both uploads at the same time, i get token mismatch exception but when i do an image upload only it works just fine. I am surely missing out on something, would could that be???

Thanks

**Comment by jrm2k6** [comment]
@andela-fokosun Great question.
Have you tried specifying `resource_type => 'video'` when uploading the video resource?
http://cloudinary.com/documentation/upload_videos#api_example_2

https://github.com/jrm2k6/cloudder/blob/master/src/JD/Cloudder/CloudinaryWrapper.php#L99

So maybe calling `upload('your-video.mp4', 'my-resource-id', ['resource_type' => 'video'])` could do the trick.

That would be my first guess. I can look at it later today or tomorrow (Pacific Time). Would it work for you?

**Comment by fokosun** [comment]
cool, yes that's fine.

**Comment by jrm2k6** [comment]
@andela-fokosun I just updated the package to include an `uploadVideo` method. It is just an alias actually calling `upload` but with the right resource_type. 
It seems to be working well on my end and it is published. Sorry for the delay.

**Comment by fokosun** [comment]
wow thanks @jrm2k6 will check that out now thanks

**Comment by jrm2k6** [comment]
I close for now. Feel free to reopen if it doesn't work.
