### ISSUE TITLE
Full API support

### ISSUE THREAD

**Issue by rogervila** [jrm2k6/cloudder#13]
Hello, I want to list all resources from Cloudinary.

I have seen that [this method](http://cloudinary.com/documentation/admin_api#list_all_images) is not declared in `CloudinaryWrapper`. If you agree, I'd like to add all the API endpoints to the wrapper.

Also, in order to make it simple, I'd follow the same API names in camel case.

For example, `destroyImages` [method](https://github.com/jrm2k6/cloudder/blob/master/src/JD/Cloudder/CloudinaryWrapper.php#L233) is calling `delete_resources` from api. I'd change the name to `deleteResources` (of course I'd mantain the current method names as an alias in order to keep compatibility)

If you agree I can make the PR. Thank you very much for this package.

**Comment by jrm2k6** [comment]
Hi @rogervila!

That sounds like a good idea. I will be happy to review the PR and make sure it is tested as needed.
Thanks again for your contribution!

**Comment by rogervila** [comment]
No problem, I will open a PR during this week.

**Comment by jrm2k6** [comment]
@rogervila Any news on this?

**Comment by rogervila** [comment]
@jrm2k6 Hello, sorry for being late. This weekend I will push at least one PR with the method alias, and later another one with the new API methods. thank you for your patience :)

**Comment by jrm2k6** [comment]
No worries, I was just wondering. Thanks!

**Comment by rogervila** [comment]
Hello, I'm being late because I am adding all Cloudinary methods and tests, instead of uploading them in different PR.

I'm also testing it in a real application, so I'm sure that it will work perfectly.

Thank you.

**Comment by jrm2k6** [comment]
No worries, I won't be fully back online until the weekend!

**Comment by jrm2k6** [comment]
Could you push what you already have? I could work on finishing it if you want

**Comment by rogervila** [comment]
Hello, the project where I needed full cloudinary support was parked, but now I need it in another project so I have finished the full api support. 

I have uploaded everything in my fork (rogervila/cloudder) and now I'm testing it in the app.
As soon as I see that it works as expected, I will make the pull request.

**Comment by jrm2k6** [comment]
Sweet. Thanks a lot.
