### ISSUE TITLE
Can you upload directly to cloudinary? 

### ISSUE THREAD

**Issue by xitude** [jrm2k6/cloudder#14]
So far all documentation is pointing to upload locally (or to s3) then download (upload) to cloudinary.

**Comment by jrm2k6** [comment]
You mean that you have to upload a resource first to your server, then upload it to s3 through Cloudinary?

**Comment by xitude** [comment]
So far the work path for files is `User > S3 > Cloudinary`. I'd prefer to go `User > Cloudinary`

**Comment by jrm2k6** [comment]
Cloudinary is working on top of S3 so I am not sure I understand.

**Comment by jrm2k6** [comment]
@xitude, actually if you upload straight from a webpage, you don't necessarily have to go through your server, and upload to cloudinary right away: http://cloudinary.com/documentation/php_image_upload#direct_uploading_from_the_browser

**Comment by jrm2k6** [comment]
@xitude Let me know if it helps, otherwise I will close this issue.

**Comment by xitude** [comment]
It does. I will close the ticket. Thanks for your help.
