### ISSUE TITLE
Download files as zip

### ISSUE THREAD

**Issue by marius-scoutsnaps** [jrm2k6/cloudder#15]
It would be great if this library would have a method to download files as zip.

http://cloudinary.com/documentation/image_upload_api_reference#generate_archive

**Comment by jrm2k6** [comment]
Hi @marius-scoutsnaps !
I know that [#13](https://github.com/jrm2k6/cloudder/issues/13) should probably cover that, but I could add it quickly in the meantime.
Will try to do it today!

**Comment by jrm2k6** [comment]
I just released a new version containing createArchive and downloadArchiveUrl. Let me know if it works.

**Comment by marius-scoutsnaps** [comment]
Thanks for the quick response. Everything works great. The only problem is, I'm getting an error ("Error parsing server response (200)") when I use Cloudder::createArchive($options, $archiveName, $mode), with $mode='download'; 

Also, when i try to create an archive with images and videos, I'm getting an error "Missing public_ids" - shows only video id. I haven't been able to figure out this issue with the original api either.

Thanks again, and keep up the good work!

**Comment by jrm2k6** [comment]
Oh, bummer. I will double check those two issues asap

**Comment by jrm2k6** [comment]
@marius-scoutsnaps Any news on that? Were you able to find a workaround for your second issue?
For the first one, I think it expects you not to return a response, but to start the download right away.
