### ISSUE TITLE
JD\Cloudder\CloudderServiceProvider not found issue.

### ISSUE THREAD

**Issue by jatinbphp** [jrm2k6/cloudder#16]
I face below problem in terminal when i run

Run php artisan vendor:publish --provider="JD\Cloudder\CloudderServiceProvider"

Command. Please Help me on this.

 [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'JD\Cloudder\CloudderServiceProvider' not found

**Comment by jrm2k6** [comment]
I just tried to install it on a fresh install. You are running windows right?
Can you paste your providers and facade array from your app.php? and your composer.json?

**Comment by jatinbphp** [comment]
No, i am using linux.

# App.php

 'providers' => [

```
    /*
     * Laravel Framework Service Providers...
     */
    Illuminate\Foundation\Providers\ArtisanServiceProvider::class,
    Illuminate\Auth\AuthServiceProvider::class,
    Illuminate\Broadcasting\BroadcastServiceProvider::class,
    Illuminate\Bus\BusServiceProvider::class,
    Illuminate\Cache\CacheServiceProvider::class,
    Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
    Illuminate\Routing\ControllerServiceProvider::class,
    Illuminate\Cookie\CookieServiceProvider::class,
    Illuminate\Database\DatabaseServiceProvider::class,
    Illuminate\Encryption\EncryptionServiceProvider::class,
    Illuminate\Filesystem\FilesystemServiceProvider::class,
    Illuminate\Foundation\Providers\FoundationServiceProvider::class,
    Illuminate\Hashing\HashServiceProvider::class,
    Illuminate\Mail\MailServiceProvider::class,
    Illuminate\Pagination\PaginationServiceProvider::class,
    Illuminate\Pipeline\PipelineServiceProvider::class,
    Illuminate\Queue\QueueServiceProvider::class,
    Illuminate\Redis\RedisServiceProvider::class,
    Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
    Illuminate\Session\SessionServiceProvider::class,
    Illuminate\Translation\TranslationServiceProvider::class,
    Illuminate\Validation\ValidationServiceProvider::class,
    Illuminate\View\ViewServiceProvider::class,
    JD\Cloudder\CloudderServiceProvider::class,,


    /*
     * Application Service Providers...
     */
    App\Providers\AppServiceProvider::class,
    App\Providers\AuthServiceProvider::class,
    App\Providers\EventServiceProvider::class,
    App\Providers\RouteServiceProvider::class,
    App\Providers\GeocodioServiceProvider::class,

    App\Providers\ResponseMacroServiceProvider::class,
    Barryvdh\Cors\ServiceProvider::class,
    Barryvdh\Debugbar\ServiceProvider::class,
    Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class,
    Dingo\Api\Provider\LaravelServiceProvider::class,
    LaravelAngular\Generators\LaravelServiceProvider::class,
    Illuminate\Html\HtmlServiceProvider::class,
    DougSisk\CountryState\CountryStateServiceProvider::class,
    Aloha\Twilio\Support\Laravel\ServiceProvider::class
],
```

  'aliases' => [

```
    'App'       => Illuminate\Support\Facades\App::class,
    'Artisan'   => Illuminate\Support\Facades\Artisan::class,
    'Auth'      => Illuminate\Support\Facades\Auth::class,
    'Blade'     => Illuminate\Support\Facades\Blade::class,
    'Bus'       => Illuminate\Support\Facades\Bus::class,
    'Cache'     => Illuminate\Support\Facades\Cache::class,
    'Config'    => Illuminate\Support\Facades\Config::class,
    'Cookie'    => Illuminate\Support\Facades\Cookie::class,
    'Crypt'     => Illuminate\Support\Facades\Crypt::class,
    'DB'        => Illuminate\Support\Facades\DB::class,
    'Eloquent'  => Illuminate\Database\Eloquent\Model::class,
    'Event'     => Illuminate\Support\Facades\Event::class,
    'File'      => Illuminate\Support\Facades\File::class,
    'Gate'      => Illuminate\Support\Facades\Gate::class,
    'Hash'      => Illuminate\Support\Facades\Hash::class,
    'Input'     => Illuminate\Support\Facades\Input::class,
    'Inspiring' => Illuminate\Foundation\Inspiring::class,
    'Lang'      => Illuminate\Support\Facades\Lang::class,
    'Log'       => Illuminate\Support\Facades\Log::class,
    'Mail'      => Illuminate\Support\Facades\Mail::class,
    'Password'  => Illuminate\Support\Facades\Password::class,
    'Queue'     => Illuminate\Support\Facades\Queue::class,
    'Redirect'  => Illuminate\Support\Facades\Redirect::class,
    'Redis'     => Illuminate\Support\Facades\Redis::class,
    'Request'   => Illuminate\Support\Facades\Request::class,
    'Response'  => Illuminate\Support\Facades\Response::class,
    'Route'     => Illuminate\Support\Facades\Route::class,
    'Schema'    => Illuminate\Support\Facades\Schema::class,
    'Session'   => Illuminate\Support\Facades\Session::class,
    'Storage'   => Illuminate\Support\Facades\Storage::class,
    'URL'       => Illuminate\Support\Facades\URL::class,
    'Validator' => Illuminate\Support\Facades\Validator::class,
    'View'      => Illuminate\Support\Facades\View::class,
    'Cloudder' => JD\Cloudder\Facades\Cloudder::class,

    'Debugbar'   => Barryvdh\Debugbar\Facade::class,
    'JWTAuth'    => Tymon\JWTAuth\Facades\JWTAuth::class,
    'JWTFactory' => Tymon\JWTAuth\Facades\JWTFactory::class,
    'Form'       => Illuminate\Html\FormFacade::class, 
    'HTML'       => Illuminate\Html\HtmlFacade::class,
    'Twilio'     => Aloha\Twilio\Support\Laravel\Facade::class,
    'Geocodio'   => Stanley\Geocodio\Geocodio::class
],
```

# 

compooser.json

{
    "name": "jadjoubran/laravel5-angular-material-starter",
    "description": "Laravel 5 angular material starter",
    "keywords": ["laravel", "angular", "material", "starter", "ui-router", "api", "angular-material"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1._",
        "barryvdh/laravel-debugbar": "~2.0",
        "tymon/jwt-auth": "0.5._",
        "dingo/api": "1.0.x@dev",
        "barryvdh/laravel-cors": "0.7.x",
        "guzzlehttp/guzzle": "^6.1",
        "laravelangular/generators": "1.5.2",
        "illuminate/html": "5.0._",
        "league/csv": "^8.0",
        "dougsisk/laravel-country-state": "^1.1",
        "predis/predis": "^1.0",
        "naviocean/laravel-nameparser": "dev-master",
        "aloha/twilio": "^2.0",
        "pda/pheanstalk": "^3.1",
        "stanley/geocodio-php": "~1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9._",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php -r \"copy('.env.example', '.env');\"",
            "php -r \"unlink('code_of_conduct.md');\"",
            "php -r \"unlink('CHANGELOG.md');\"",
            "php -r \"unlink('.codeclimate.yml');\"",
            "php -r \"unlink('.travis.yml');\"",
            "php artisan key:generate",
            "php artisan jwt:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
( i have not made any changes in composer.json) Just follows your steps.

Thanks.

**Comment by jrm2k6** [comment]
I don't see jrm2k6/cloudder in your composer.json are you sure you required it?

**Comment by jatinbphp** [comment]
Below is my new composer.json, then i fire composer update but still get same error

{
    "name": "jadjoubran/laravel5-angular-material-starter",
    "description": "Laravel 5 angular material starter",
    "keywords": ["laravel", "angular", "material", "starter", "ui-router", "api", "angular-material"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1._",
        "barryvdh/laravel-debugbar": "~2.0",
        "tymon/jwt-auth": "0.5._",
        "dingo/api": "1.0.x@dev",
        "barryvdh/laravel-cors": "0.7.x",
        "guzzlehttp/guzzle": "^6.1",
        "laravelangular/generators": "1.5.2",
        "illuminate/html": "5.0._",
        "league/csv": "^8.0",
        "dougsisk/laravel-country-state": "^1.1",
        "predis/predis": "^1.0",
        "naviocean/laravel-nameparser": "dev-master",
        "aloha/twilio": "^2.0",
        "pda/pheanstalk": "^3.1",
        "stanley/geocodio-php": "~1.0",
         "cloudinary/cloudinary_php": ">=1.1"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9._",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\": "app/"
        },
         "psr-0": {
            "JD\Cloudder": "src/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php -r \"copy('.env.example', '.env');\"",
            "php -r \"unlink('code_of_conduct.md');\"",
            "php -r \"unlink('CHANGELOG.md');\"",
            "php -r \"unlink('.codeclimate.yml');\"",
            "php -r \"unlink('.travis.yml');\"",
            "php artisan key:generate",
            "php artisan jwt:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

**Comment by jrm2k6** [comment]
There is still no jrm2k6/cloudder in there.
You need this in there somewhere: "jrm2k6/cloudder": "*"

**Comment by jatinbphp** [comment]
Thanks for your quick feedbacks.
I have manage it with another approach for now.

**Comment by jrm2k6** [comment]
@jatinbphp How did you work around it? I just felt like your composer.json was wrong, meaning you were not pulling the package correctly
