### ISSUE TITLE
Folder Creation on upload

### ISSUE THREAD

**Issue by xitude** [jrm2k6/cloudder#18]
As title, how do you create a folder (with name) on upload.
`E.g. /profiles/{user}/avatar/{avatar}.jpg`

**Comment by jrm2k6** [comment]
Sorry, I am quite busy today, I will try to get a response for you soon!

**Comment by jrm2k6** [comment]
@xitude Have you tried specifying `folder` as part of the options when calling the upload method?

http://cloudinary.com/documentation/upload_images#api_example_4

**Comment by xitude** [comment]
Ah perfect I got it working. 🍡

**Comment by oluwajubelo1** [comment]
@xitude , please can you give me a working example. I'll be grateful. Thanks in anticipation
