### ISSUE TITLE
Upgrade to Laravel5

### ISSUE THREAD

**Issue by jrm2k6** [jrm2k6/cloudder#2]

**Comment by azulkipli** [comment]
Thank you for creating this package, please let me know when package for Laravel 5 ready

**Comment by jrm2k6** [comment]
I might be able to work on that this weekend! We are still using laravel 4.2 at my work so I was planning on upgrading it when we would have upgraded but I guess I have to do it before! :D Thanks for reaching out!

**Comment by isaackearl** [comment]
I am also hoping to use this package for laravel 5.  I would also like to contribute to the project once it supports laravel 5.

**Comment by jrm2k6** [comment]
@isaackearl great! I will try to come up with an upgrade asap. Busy with work, but hey, I need to take some time to get done with the L5 upgrade.

**Comment by jrm2k6** [comment]
@isaackearl @azulkipli I released a version of the package that should work with Laravel 5. I also have a sample project here, using it: https://github.com/jrm2k6/cloudder-l5-sample-project
I was able to upload and delete images, and the unit tests are passing so the rest of the features should work just fine.
The README should contain all the information needed to use the package with Laravel 5.

**Comment by azulkipli** [comment]
thanks for your great work,

I will check it asap

**Comment by azulkipli** [comment]
Hi again,
When I do this;
<code>
composer require jrm2k6/cloudder
</code>

it require 0.1.\* version

I set service provider & facade alias then try to publish config it give error.

<code>
[BadMethodCallException]  
  Call to undefined method [package]
</code>

So I use as in the example project you post above
<code>
"jrm2k6/cloudder": "dev-l5"
</code>

In the sample project no code that you already have written as example :(

**Comment by jrm2k6** [comment]
Hey,
did you try this: `composer require jrm2k6/cloudder:0.1.*:dev-l5`
I specify the L5 instructions here: https://github.com/jrm2k6/cloudder/tree/l5
I know there might be a problem with composer and branch aliases (my Travis CI integration fails but it should still work).

Let me know if it works or not. If not, I will fix it tonight after my workday.

**Comment by azulkipli** [comment]
Ive tried
`composer require jrm2k6/cloudder:0.1.*:dev-l5`
Give me
`no matches found: jrm2k6/cloudder:0.1.*:dev-l5`

**Comment by jrm2k6** [comment]
You forgot the *.

`composer require jrm2k6/cloudder:0.1.*:dev-l5`

**Comment by azulkipli** [comment]
ofcourse not when executing it on my CLI, 

it just filtered out when editing on github markdown previously i didnt use ``

**Comment by jrm2k6** [comment]
Ok I will check then.! Sorry for that

**Comment by jrm2k6** [comment]
@azulkipli So I just tried:

`composer require jrm2k6/cloudder dev-l5` should work. Can you confirm?

**Comment by jrm2k6** [comment]
@azulkipli any news?

**Comment by num3thod** [comment]
Can confirm that `composer require jrm2k6/cloudder dev-l5` worked for me.

**Comment by jrm2k6** [comment]
Great! Let me know if you need any new features. I am not using Cloudinary
anymore, but happy to implement stuff you need!

On Wed, Jun 10, 2015 at 5:52 PM, Michel Raymond notifications@github.com
wrote:

> Can confirm that composer require jrm2k6/cloudder dev-l5 worked for me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jrm2k6/cloudder/issues/2#issuecomment-110957268.

## 

Jérémy Dagorn
www.jeremydagorn.com

Android apps I developed:
https://play.google.com/store/apps/developer?id=JumyApps

**Comment by num3thod** [comment]
Wow. Thanks, bud. I'm incorporating into an L5.1 project. Let you know how it goes.

**Comment by jrm2k6** [comment]
There shouldn't be any issue as the differences between 5 and 5.1 aren't
related to Middleware as far as I can tell.

**Comment by jrm2k6** [comment]
@num3thod How did it go? If it works for you I will close this issue and merge the branch l5 to master so we don't have to use dev anymore.

**Comment by num3thod** [comment]
Still working on it. I'll let you know by tomorrow at the latest.

**Comment by jrm2k6** [comment]
@num3thod Any news?

**Comment by jrm2k6** [comment]
I close it for now. Feel free to reopen.

**Comment by fingertips-solutions** [comment]
which version we have to use for laravel 4.2. i installed it and getting this error 
Call to undefined method JD\Cloudder\CloudderServiceProvider::publishes()

**Comment by jrm2k6** [comment]
@fingertips-solutions  You should have opened a new issue.

But you should just have to follow this: https://github.com/jrm2k6/cloudder#installation
