### ISSUE TITLE
Codeclimate suggestions

### ISSUE THREAD

**Issue by rogervila** [jrm2k6/cloudder#23]
Hello,

I've been working with the library and it works really well.

Just for curiosity, I added my fork to codeclimate, and it suggests to reduce the amount of methods on `CloudinaryWrapper.php`

The link: https://codeclimate.com/github/rogervila/cloudder/issues

Do you think that moving the methods into traits could be a good idea?

This are the current badges:

[![Code Climate](https://codeclimate.com/github/rogervila/cloudder/badges/gpa.svg)](https://codeclimate.com/github/rogervila/cloudder)
[![Test Coverage](https://codeclimate.com/github/rogervila/cloudder/badges/coverage.svg)](https://codeclimate.com/github/rogervila/cloudder/coverage)
[![Issue Count](https://codeclimate.com/github/rogervila/cloudder/badges/issue_count.svg)](https://codeclimate.com/github/rogervila/cloudder)

**Comment by jrm2k6** [comment]
Yes traits would be a great solution to avoid too many methods in one class.

**Comment by rogervila** [comment]
I'm making some tests on my fork.

**Comment by jrm2k6** [comment]
Do you need any help from me? I feel bad you are doing everything on your own ahah!

**Comment by rogervila** [comment]
haha well, maybe you could make a 'refactoring' branch, where I can make pull requests in order to test the best way to refactor the whole code

**Comment by jrm2k6** [comment]
Done. Let me know if I can help besides just reviewing.

**Comment by rogervila** [comment]
Could you split the tests in different ones by its kind?
