### ISSUE TITLE
Is there support for unsigned_upload

### ISSUE THREAD

**Issue by SahilDude89ss** [jrm2k6/cloudder#24]
Is there support for unsigned_upload like \Cloudinary\Uploader::unsigned_upload ?

**Comment by jrm2k6** [comment]
No right now, as far as I can tell. That shouldn't be hard to add, we just didn't have the need for it. Do you know how it is used exactly? It says it won't go through your server if you use an unsigned_upload, can you tell me more about it? http://cloudinary.com/documentation/upload_images#unsigned_upload. That would be useful only if you run a program using cloudder from the cli right?

**Comment by jrm2k6** [comment]
@SahilDude89ss  You can try to double check if it works, use the branch ```issue-24-unsigned-upload```
