### ISSUE TITLE
Not working for Lumen (5.4)

### ISSUE THREAD

**Issue by ghost** [jrm2k6/cloudder#28]
I know that the documentation in this repo says it works for Laravel 5. That said, I was trying to use this in a Lumen 5.4 project and fails when trying to register the service provider:

`Fatal error: Call to undefined method Laravel\Lumen\Application::share() in /var/www/nike/vendor/jrm2k6/cloudder/src/JD/Cloudder/CloudderServiceProvider.php on line 41`

this is exactly at:
```
    public function register()
    {
        $this->app['cloudder'] = $this->app->share(function ($app) {
            return new CloudinaryWrapper($app['config'], new Cloudinary, new Cloudinary\Uploader, new Cloudinary\Api);
        });
    }
```

Any ideas if that `app->share()` can be changed to something else?

Thanks!

**Comment by jrm2k6** [comment]
Hi, thanks for opening an issue. Another thread is already going on here https://github.com/jrm2k6/cloudder/issues/27 about the Laravel 5.4 compatibility! I should get to it tonight after my work day! Is that OK?

**Comment by ghost** [comment]
Oh snap! I totally missed that. Sorry! 😄 
That issue is caused by the `Application::share()` method, same as this one, so you can close this thread since is the same thing.
Btw, good job with this package!

Cheers!

**Comment by jrm2k6** [comment]
No worries! Thanks
