### ISSUE TITLE
GIF images is getting returned as PNG

### ISSUE THREAD

**Issue by the94air** [jrm2k6/cloudder#31]
GIF images return PNG when using the `Show` method. Like this image
https://res.cloudinary.com/codehelper/image/upload/c_fit,h_538,w_538/NDda9oGEDR3LY.png
I want to return it as
https://res.cloudinary.com/codehelper/image/upload/c_fit,h_538,w_538/NDda9oGEDR3LY.gif

**Comment by jrm2k6** [comment]
Hi,
Can you provide a code snippet showing how you upload your resource, and how you call the show method on it? Just to help reproducing the issue?

Thanks!

**Comment by the94air** [comment]
The upload
```php
        $gravatar = $request->file('gravatar');
        $imageId = Hashids::encode(Auth::user()->id).str_random(11);
        Cloudder::upload($gravatar->getPathName(), $imageId);
```
Show image
```blade
{{ Cloudder::secureShow(Auth::user()->gravatar, ["width" => 538, "height" => 538, "mode" => "limit"]) }}
```
I have check my Cloudinary and the image is a GIF file the same as I uploaded image.

**Comment by jrm2k6** [comment]
Thanks @the94air, I will check that tonight.

**Comment by the94air** [comment]
What do you think the problem? does the show method get the image extension for Cloudinary cloud? Sorry I am just confused `^_^` :+1:

**Comment by jrm2k6** [comment]
The problem could be related to the upload options. Maybe you need to
specify an option like 'auto' or something like that. Without running the
code it is hard to say.

**Comment by jrm2k6** [comment]
@the94air So I double checked. I was able to upload a gif, and getting the url for the uploaded resource. The uploaded resource appears to be a gif (http://res.cloudinary.com/jdcloudder/image/upload/v1494988349/mypikachu.gif)

You can see the implementation here: https://github.com/jrm2k6/cloudder-l5-sample-project/commit/f6151a88895f03f4b9d07f5a75e892d7206a3fea

Let me know if it helps. Maybe you could send me the image you are trying to upload also, through email or something?

**Comment by the94air** [comment]
Sorry for the late reply. I couldn't reach my PC for 2 days (I wouldn't survive if i reach the third day :joy: ).
I have tried to do this (I said maybe the problem form the temp path) but also the same problem
```php
$gravatar = $request->file('gravatar');
$imageId = Hashids::encode(Auth::user()->id).
                    str_random(11);

$TempPath = $request->file('gravatar')->store('gravatar');

$imagePath = storage_path("app/$TempPath");

Cloudder::upload($imagePath, $imageId);

File::delete($imagePath);
```
I can't find any way to get arround this. :crying_cat_face: Help.

**Comment by jrm2k6** [comment]
Without having the same image it is hard. Can you try it with the pikachu image I used? http://res.cloudinary.com/jdcloudder/image/upload/v1494988349/mypikachu.gif
Just download it, put in in your public folder, and look at the code I used, to see if what I did works for you.
If it does, we can narrow down the possibilities for error.

**Comment by the94air** [comment]
Yes, I have used you image as you said before

**Comment by the94air** [comment]
First i created this route to upload the image form the storage/app/gravatar directory 
```php
Route::get('/img', function () {
    Cloudder::upload(storage_path('/app/gravatar/OJvEYLFiVM7oUSL333Vl4ehwGyBbX3qjd5kZ0IDb.gif'), []);
});
```
And in my account I received that image as GIF as you see
![1](https://cloud.githubusercontent.com/assets/18303390/26213069/5ffd9c90-3c00-11e7-8bcc-9bb304d2415b.png)
Then I created this route to show the image link
```php
Route::get('/imgshow', function () {
    echo Cloudder::secureShow('vble44qdnk7ipvktobow', []);
    echo '<br>';
    echo Cloudder::show('vble44qdnk7ipvktobow', []);
});
```
the result
```
https://res.cloudinary.com/codehelper/image/upload/c_fit,h_150,w_150/vble44qdnk7ipvktobow.png
http://res.cloudinary.com/codehelper/image/upload/c_fit,h_150,w_150/vble44qdnk7ipvktobow.png
```
I don't think the problem in the upload because the image work perfectly after the uploading and Cloudinary does recognize that image as GIF even If I open it on browser. the problem in the image show method.
I hope this is helpful.

**Comment by jrm2k6** [comment]
Weird. My show method worked perfectly fine. I can try to debug that more. The only different you and I have is that you upload from storage and I upload from public. But even though, it looks like the image on cloudinary that you uploaded is fine.

**Comment by the94air** [comment]
In composer I am using this version `"jrm2k6/cloudder": "0.4.*",` and I also tried to upload your image from public directory but also the same png result.

**Comment by jrm2k6** [comment]
The other difference is that I do it from a console command, while you do it from a controller but it shouldn't make any difference.

**Comment by the94air** [comment]
I can't find the problem. so i decided to save image extension in to the database and use the value inside the show method.
```php
Cloudder::secureShow('wegjezbygias86stouhw', ["format" => "gif"]);
```

**Comment by the94air** [comment]
It looks like I am the only one having this problem. I am going to close it for now. Thanks for spending the time to solve me issue @jrm2k6 `^_^`.

**Comment by jrm2k6** [comment]
I will still try to get to the bottom of the issue. Sorry for not fixing.
