### ISSUE TITLE
Questions about adding features

### ISSUE THREAD

**Issue by benyanke** [jrm2k6/cloudder#35]
I'm really loving your Cloudder lib, and I'll be using it for a few of our corporate projects. One thing I want to add is a specified base url for uploads, so that all files, by default, get uploaded to a subdirectory in cloudinary (for example, I could specify `CLOUDINARY_BASE_UPLOAD_URL=/marketing/` to upload all pictures to a marketing folder on cloudinary. 

Similarly, I'd like to also implement `CLOUDINARY_TAGS_ON_UPLOAD`, which would specify a list of tags applied to all uploads - of course, more could be specified on each individual one, but in my case, I could - for example - add `marketingmedia` tag to all uploads without specifying it.

Are those things you'd accept a PR for if I implemented them in the main library, or should I just implement my own simple wrapper?

**Comment by jrm2k6** [comment]
I am hesitant to force people to specify env variables if they are not mandatory.
It should be easy to have a method/class wrapper around Cloudder that will set the different variables you want when using Cloudder?

What do you think?

**Comment by benyanke** [comment]
If I were to implement them within the lib itself, it would certainly be optional, not required. In other words, no downsides (beyond a bit of extra code) for those who don't want it, and upsides for those who do

**Comment by jrm2k6** [comment]
I am open to see an implementation of it as I am not 100% sure of how it would look.

**Comment by benyanke** [comment]
Sounds good - I'll implement when I get back to this section @ work, PR, and we can discuss then

**Comment by rheedwahn** [comment]
got this error "Array to string conversion" when using the transformation to add watermark to my images

**Comment by jrm2k6** [comment]
@rheedwahn You might want to open a new issue for that
