### ISSUE TITLE
Support package auto-discovery for Laravel 5.5

### ISSUE THREAD

**Issue by jrm2k6** [jrm2k6/cloudder#36]

**Comment by nrthbound** [comment]
Sorry to be a bother, but has this been worked on at all? If not, could you point me in the direction to make it functional with 5.5/5.6 so I can update it and get a PR going? Would love to use this in a current project I'm working on. Thanks!

**Comment by jrm2k6** [comment]
@tetshi I haven't had a chance yet no. Would be awesome if you could give it a shot.
This is an example of what needs to be done:
https://github.com/barryvdh/laravel-debugbar/pull/643/files

I will add some more official links here when I have a few minutes.

Official doc: https://laravel.com/docs/5.5/packages#package-discovery

**Comment by joseraul** [comment]
Hi, I guess this is not done yet, right? I will be happy to help. With the permission of tetshi, I will commit a PR ~~in a few days~~ now: #45
