### ISSUE TITLE
Disable Scaling (Or set height to auto)

### ISSUE THREAD

**Issue by ahmadyousefdev** [jrm2k6/cloudder#37]
Hi!
the default scaling is
```
'scaling'    => [
        'format' => 'png',
        'width'  => 150,
        'height' => 150,
        'crop'   => 'fit',
        'effect' => null
    ],
```
So when I want to show an image - using `Cloudder::show()` -, it will take these default values unless I change them in each photo show command.

But sometimes I don't know the height or the width. I need to make them = auto to solve this problem.

How can I do that?

Thanks !

**Comment by jrm2k6** [comment]
Hm I don't know from the top of my head. I can definitely check the Cloudinary docs where I think the answer is.

**Comment by ahmadyousefdev** [comment]
I managed to solve this problem by changing the scaling in config to
```
'scaling'    => [
        'format' => 'png',
        'width'  => 'auto',
        //'height' => , REMOVE HEIGHT
        'crop'   => 'fill', // change crop to fill
        'effect' => null
    ],
```

Thank you so much !
