### ISSUE TITLE
Folder is not created in after passing the path in public id

### ISSUE THREAD

**Issue by prabhat2k15** [jrm2k6/cloudder#40]
I original documentation we can pass the folder/file.jpg and it uploads the file in that particular folder. But in this wrapper when i pass like so it treats it as file name .

Please tell me the solution . I needed it urgently.

**Comment by jrm2k6** [comment]
Hi,
Sorry I didn't get an email about this issue.
Let me check and get back to you.

**Comment by jrm2k6** [comment]
@prabhat2k15 You need to make sure you have the Auto-create folder option enabled on Cloudinary:
https://cloudinary.com/console/settings/upload or that you have manually created that folder in your media library

**Comment by oluwajubelo1** [comment]
@jrm2k6 , i've enabled Auto-create folder option on cloudinary but still am unable to create a folder via an API call. Below is my code:

\Cloudinary\Uploader::upload($fileName,[
                   "folder"=>"test-folder/"
                ]);
