### ISSUE TITLE
How to add the multiple files upload option

### ISSUE THREAD

**Issue by odagora** [jrm2k6/cloudder#42]
Hi, I've implemented your wrapper and tested it for the last days and I love it. I have only one question and is how to add the "multiple files upload" feature?. I've read the documentation and it mention the $options array to add additional features, but in this case how could I do it?

Thanks

**Comment by jrm2k6** [comment]
Hi,
Sorry for the delay. I still don't know why I am not receiving emails for issues created.
Let me check and I will get back to you!

**Comment by jrm2k6** [comment]
@ogonzalez29 It doesn't look like server-side uploading supports multiple files.
https://cloudinary.com/documentation/image_upload_api_reference#upload

The multiple files options is if you are doing resource uploads straight from your browser, not through your backend: https://cloudinary.com/documentation/upload_images#direct_uploading_from_the_browser_or_mobile_application.
