### ISSUE TITLE
Must supply api_key Laravel

### ISSUE THREAD

**Issue by HamzaNaciri** [jrm2k6/cloudder#46]
Hello I'm trying to do something like :
Cloudder::upload($filename);
            $c=Cloudder::getResult();
            dd($c);

in my controller but I get error message "Must supply api_key", I don't get where the problem came from, I specified my api key, my secret api and the cloud name.. Can I get any help please?

**Comment by jrm2k6** [comment]
What version of the package are you using?
When you say you specified everything, do you mean that:
```
CLOUDINARY_API_KEY=API_KEY
CLOUDINARY_API_SECRET=API_SECRET
CLOUDINARY_CLOUD_NAME=API_CLOUD_NAME
``` 
is in your .env?

**Comment by HamzaNaciri** [comment]
Thanks for the quick answer ! I’m using Laravel 5.6.12

And yes I specified

CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=
CLOUDINARY_CLOUD_NAME=

In my .env

Hamza NACIRI FARID
227797@supinfo.com<mailto:227797@supinfo.com>




Le 24 avr. 2018 à 22:32, Jeremy Dagorn <notifications@github.com<mailto:notifications@github.com>> a écrit :

What version of the package are you using?

**Comment by HamzaNaciri** [comment]
Any suggestions @jrm2k6  ?

**Comment by jrm2k6** [comment]
Oh sorry I guess my other comment didn't post. I am at work, I can check tonight. One thing I would do is put a breakpoint in here https://github.com/jrm2k6/cloudder/blob/master/src/JD/Cloudder/CloudinaryWrapper.php#L59 (or a log statement and see what the config call returns.

**Comment by HamzaNaciri** [comment]
No problem ! I tried to dd my config and that's what I got :
<img width="564" alt="cloudinary" src="https://user-images.githubusercontent.com/28985726/39265122-beab12ee-48c6-11e8-90f4-0072ab9ed88d.png">

It seems weird cause I set up my credentials in the .env.. ?

**Comment by jrm2k6** [comment]
Alright, that helps. I will try to get back to you today or tomorrow. Is that ok? In the meantime, you can try to do that https://github.com/jrm2k6/cloudder#optional.
It could be related to package autodiscovery.

**Comment by HamzaNaciri** [comment]
Oh okey ! Sounds good to me. I already did yesterday when I installed cloudder, I added 
' providers' => array(
  'JD\Cloudder\CloudderServiceProvider'
);

'aliases' => array(
  'Cloudder' => 'JD\Cloudder\Facades\Cloudder'
);
to my config/app.php !

**Comment by jrm2k6** [comment]
oh, then try to remove it. You shouldn't have to do this as from Laravel 5.5 you can use package discovery.

**Comment by HamzaNaciri** [comment]
I removed it, installed the package "composer require barryvdh/laravel-debugbar:dev-master" and got :

> Discovered Package: jrm2k6/cloudder

but always getting null values on the 3 credentials !

**Comment by jrm2k6** [comment]
So I create a new project:

```
composer create-project --prefer-dist laravel/laravel test-laravel
composer require cloudder/jrm2k6
```

And then I created a new command:
```
<?php namespace App\Console\Commands;

use Illuminate\Console\Command;
use JD\Cloudder\Facades\Cloudder;

class UploadPictureCommand extends Command {

    protected $PICTURE_NAME;
	/**
	 * The console command name.
	 *
	 * @var string
	 */
	protected $name = 'cloudder:upload_image';

	/**
	 * The console command description.
	 *
	 * @var string
	 */
	protected $description = 'Uploads an image to Cloudinary.';

	/**
	 * Create a new command instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		parent::__construct();
        $this->PICTURE_NAME = public_path('pikachu.gif');
	}

	/**
	 * Execute the console command.
	 *
	 * @return mixed
	 */
	public function handle()
	{
        Cloudder::upload($this->PICTURE_NAME,  'random/sss', [])->getResult();
	}
}
```
And it seems to be working fine.

Is your code open-source? I might be able to run it if it is accessible.

**Comment by joseraul** [comment]
Hi HamzaNaciri!

Can you try 
`dd(env('CLOUDINARY_API_KEY'));`
in any place in your project? Because if it is still "null" I don't think it is a problem of the package. Maybe dirty cache or something like that...

**Comment by HamzaNaciri** [comment]
Actually it's a school project and it's forbidden to put it on GitHub ! What we can do is I can give you my TeamViewer credentials, so you can run it from my pc ! If you agree of course. @jrm2k6 

Hello @joseraul !
I tried : 
`dd(env('CLOUDINARY_API_KEY'));
`
and it still giving null even though I run :
`php artisan cache:clear` !

**Comment by HamzaNaciri** [comment]
Okeeey I solved the issue, it was a problem of config cache ! I just run :
`php artisan config:clear`
Now I'm getting the values of my credentials ! Thanks !

**Comment by jrm2k6** [comment]
Thanks @joseraul for the hint! :)
