### ISSUE TITLE
Upload preset must be specified when using unsigned upload

### ISSUE THREAD

**Issue by sushantlp** [jrm2k6/cloudder#50]
Hi,
 i am using laravel 5.5 and using 0.4.* cloudder. when i upload image my server to cloudinary server error return " Upload preset must be specified when using unsigned upload ".

**Comment by jrm2k6** [comment]
Hi @sushantlp 
Could you paste some of the code you have?

**Comment by sushantlp** [comment]
hi @jrm2k6 
this is my code

  try {
            
            $status = $this->status;
            $medi = new MediController();
            $database = new DatabaseSaver();
            
            if ($status == 1) {
                
                $response = Cloudder::upload($this->filePath,$this->publicId,array("folder"=>$this->folder,"use_filename"=>TRUE ,"unique_filename"=>FALSE))->getResult();
                
                if ($response) {
                    
                    // Return Cloudinary Image Url
                    $path = $response['secure_url'];
                    
                    $response = $medi->processMerchantMenuPicUpload($this->data,$path);
                    if (!$response) {
                        return false;
                    }
                    return true;
                }
            }
        } 
        catch(\Exception $e) {
            
            $database->errorLog('Exception In GlobalCloudinaryImageUpload Job()',$e->getMessage());
            
            return false;
        }

**Comment by jrm2k6** [comment]
Are you sure your .env file has the correct credentials?
