### ISSUE TITLE
How to resize image

### ISSUE THREAD

**Issue by yamenshahin** [jrm2k6/cloudder#51]
I created this function

Cloudder::upload($image, $path, array("width"=>150, "height"=>150, "crop"=>"scale") );

But it not work

**Comment by jrm2k6** [comment]
@yamenshahin Will check and get back to you! :)

**Comment by jrm2k6** [comment]
It seems to be working for me with this:
```
Cloudder::upload($pathToFile,  'publicIdUploadedPcture', ["width" => 800, "height" => 600, "crop" => "limit"]);
```

Could it be because you have the parameter in the wrong order? You have `$image, $path` where it should be `$pathToImage, $publicId`

**Comment by jrm2k6** [comment]
@yamenshahin Closing for now.
