### ISSUE TITLE
Invalid Signature d4cc2506fe374f2c10de3de3368964825acac78e. String to sign 

### ISSUE THREAD

**Issue by elmage** [jrm2k6/cloudder#53]
I get the following error when I try to use `Cloudder::upload($file, $file_id)`  method: `Invalid Signature d4cc2506fe374f2c10de3de3368964825acac78e. String to sign - 'public_id=1737aa5b068205e4de112932503b844a8bf62fe5&timestamp=1528755130'.`

**Comment by jrm2k6** [comment]
What version of Laravel are you using?
Are you sure you have set up the Cloudinary credentials correctly?

**Comment by elmage** [comment]
I found the issue. I always forget that you have to restart the server whenever entries are changed in the .env file so I was using wrong credentials.

**Comment by jrm2k6** [comment]
Great! 👍
