### ISSUE TITLE
Cannot delete file with the delete() method

### ISSUE THREAD

**Issue by mbengchan** [jrm2k6/cloudder#56]
i am unable to delete files using the methods provided. Here is my code:

`Cloudder::delete($publicId, null);`

Or

`Cloudder::delete($publicId, array('folder' => 'users/'));`

no error but when i check my dashboard file is still there.

**Comment by jrm2k6** [comment]
Hi @Shadomax Thanks for opening an issue. Let me give it a look.

**Comment by jrm2k6** [comment]
It seems to be working fine for me. I tried using delete and destroyImage and it deletes the picture correctly.
Are you sure the publicId you are passing is the correct one?
delete / destroyImage returns a boolean if the deletion was successful, can you verify the return value of your call?

**Comment by mbengchan** [comment]
It's working fine when i don't upload into a folder. But when i upload into a folder the delete doesn't work

**Comment by mbengchan** [comment]
@jrm2k6 please can i see your example of deleting a picture found in a folder called samples.
Here is the directory structure: `samples/test.png`

How do you delete such a file. Please for the syntax

**Comment by jrm2k6** [comment]
Sure, sorry for not replying earlier. I don't get notification emails for some reason.

**Comment by jrm2k6** [comment]
I just pass the public id (in the case of the example: `Cloudder::delete('samples/test.jpg);`

**Comment by mbengchan** [comment]
Thanks very much. I would try and notify you if it works.

**Comment by renatoagomes** [comment]
Probably not related, but since i just dealed with this:

In the case you're binding model events to some sort of Photo model, make sure you're calling the `->delete()` on the model instance, not in the QueryBuilder witch doesnt trigger the deleting/deleted events  ¬¬'

**Comment by mbengchan** [comment]
Thanks @jrm2k6 it worked.

**Comment by JCarlosR** [comment]
What's the difference between `delete` and `destroyImage`?
