### ISSUE TITLE
Error While Uploading Audio

### ISSUE THREAD

**Issue by mbengchan** [jrm2k6/cloudder#57]
Hey guys, am having issue uploading audio to Cloudinary. I use the Method bleow

```
$file = $request->file('file')->getRealPath();

Cloudder::upload($file, null, ['resource_type' => 'video']);

$song_url = Cloudder::secureShow(Cloudder::getPublicId());

// the value of $song_url == "https://res.cloudinary.com/mad237/image/upload/c_fit,h_150,w_150/tqgd6r6jpquhqq5hbmua.png"
```

Please i need your help the file am uploading is an audio file.

**Comment by jrm2k6** [comment]
Wait, are you uploading a video or an audio file? Your code and issue title are not matching with the description of your problem.

**Comment by mbengchan** [comment]
yeah i noticed. but i have resolve the issue. When i checked the documentation the cloudinary API is build from ground up to support images so if you ever needed to upload any other file whic is not an image file you will have to specify the type in the `resource_type` option and set **scaling options to null** so here is how i was supposed to upload the audio file and get the write file name.

Here is the correct code

```
$file = $request->file('file')->getRealPath();

$file = $request->file('file')->getRealPath();

$songUpload = Cloudder::uploadVideo($file, null, ['resource_type' => 'video']);

$song_url = Cloudder::secureShow(Cloudder::getPublicId(), ['resource_type' => 'video', 'format' => 'mp3', "width" =>  null, "height"=> null, "crop" => null]);

// the value of $song_url == "https://res.cloudinary.com/mad237/video/upload/tqgd6r6jpquhqq5hbmua.mp3"
```

And everything is working perfectly.
