### ISSUE TITLE
Must Supply API KEY

### ISSUE THREAD

**Issue by JamieBunyassi** [jrm2k6/cloudder#58]
I am experiencing an issue reported in another thread and the solutions listed there do not seem to solve. Kindly offer any assistance you may have on how to resolve this issue.

![screenshot from 2018-09-13 04 55 02](https://user-images.githubusercontent.com/15850138/45462593-379a8280-b711-11e8-900f-00befd677b49.png)

**Comment by jrm2k6** [comment]
Hi @JamieBunyassi !

How does your .env look like? 
Do you have all the right properties for cloudinary in there?

**Comment by JamieBunyassi** [comment]
Hello, I solved it by reverting to an older version of the cloudinary_php
composer package. It appears Cloudinary may have made changes during the
recent update that don't coincide with the cloudder package.

**Comment by jrm2k6** [comment]
Oh interesting. Thanks for checking. What version of cloudinary_php did you have to pinpoint to?
I will check to see what those differences are and release a new major version

**Comment by JamieBunyassi** [comment]
1.1.10, I am not close to my computer but I think that's the version that
got it to work.

**Comment by jrm2k6** [comment]
I just tried with the latest version of cloudinary/cloudinary_php - 1.11.1 and uploading seems to be working fine. Were you running a specific cloudinary operation?

**Comment by chcourses** [comment]
Same here. Laravel 5.7 and PHP 7.2.11.
