### ISSUE TITLE
Adding secure => true globally

### ISSUE THREAD

**Issue by Migweld** [jrm2k6/cloudder#6]
Just wondering if there's a way to add `secure => true` to the options array globaly so that all requests are made using HTTPS? If not, would it be possible to add this in? Happy to submit a PR.

**Comment by Migweld** [comment]
Nevermind, found you can put `secure =>  true` inside the scaling array of the config and it'll apply it globally

**Comment by jrm2k6** [comment]
Raa, I didn't even get an email for this one. Time to recheck my gmail filters!
