### ISSUE TITLE
On the fly transformations

### ISSUE THREAD

**Issue by nwaughachukwuma** [jrm2k6/cloudder#62]
Hi @jrm2k6 please is it possible to achieve on the fly (OTF) transformation using this package? If yes, can you provide an example on how to? Thanks so much

**Comment by jrm2k6** [comment]
@nwaughachukwuma You should be able to pass a transformation array as part of the options when calling the upload method.
What time of transformation are you looking to do? I can try to give you a working example if you give me more context.

**Comment by dlakes** [comment]
@jrm2k6 An Example code  for Image Transformation to reduce the size of the image saved on cloudinary would be of help.

**Comment by jrm2k6** [comment]
@diakes You mean something like this: https://cloudinary.com/documentation/image_transformations#adjusting_image_quality?

**Comment by nwaughachukwuma** [comment]
Thanks @jrm2k6 this works
