### ISSUE TITLE
Upload to specific folder

### ISSUE THREAD

**Issue by oluwajubelo1** [jrm2k6/cloudder#63]
Good day, 
Please, how can i upload to a specific folder on cloudinary. For example, if i have a folder name banners, how can i upload images directly from my laravel code to banners folder? Thanks

**Comment by oluwajubelo1** [comment]
hey @jrm2k6 , is there a way i can solve this issue? Thanks in anticipation

**Comment by jrm2k6** [comment]
@oluwajubelo1 Did you check those closed issues for a solution: https://github.com/jrm2k6/cloudder/issues/40 and https://github.com/jrm2k6/cloudder/issues/18?

**Comment by oluwajubelo1** [comment]
@jrm2k6 , yes i have. What i want is to upload to an already created folder on media library. For example, i have a folder named banners, so programmatically, i want to upload images to banners folder which has already been created. Thanks

**Comment by oluwajubelo1** [comment]
Thanks @jrm2k6 , i've been able to solve my issue regarding uploading to folder. Another thing i'm looking at is how to rename a folder on cloudinary via API call with the images inside the folder still the same. Thanks

**Comment by jrm2k6** [comment]
What was the solution you used for your first problem?
For your second problem it looks like you have to rename all resources within the folder to match the new name -> https://support.cloudinary.com/hc/en-us/articles/202521002-How-to-move-an-image-from-one-folder-to-another-

**Comment by oluwajubelo1** [comment]
For the first problem, it was the order in which i passed in the variables into the upload method that was wrong. Below is a sample code:
   Cloudder::upload($imageName,null,[
                    "folder"=>$categoryName
                ]);

**Comment by jrm2k6** [comment]
Sounds good. Feel free to close the issue if it is all good on your side.
