### ISSUE TITLE
Server returned unexpected status code - 0 -

### ISSUE THREAD

**Issue by Aamish99** [jrm2k6/cloudder#64]
Getting Server returned unexpected status code - 0 - when i am trying to upload any image. Here is my code 
Cloudder::upload($filename, null);

**Comment by jrm2k6** [comment]
Do you have the right configuration in your .env?
What version of Laravel and cloudder?

**Comment by seyidaniels** [comment]
I am also having this error

**Comment by seyidaniels** [comment]
> Getting Server returned unexpected status code - 0 - when i am trying to upload any image. Here is my code
> Cloudder::upload($filename, null);

Try using another browser, the image file is not getting to where you would send it to Cloudinary

**Comment by jrm2k6** [comment]
What version of Laravel and cloudder are you running?
Where is $filename coming from? Could you paste some more code?

**Comment by smouki** [comment]
hey I'm getting that kind of error while uploading videos.. images are fine. did you solve the problem?
its when using the cloudinary WP plugin via Media Library.
