### ISSUE TITLE
Cloudder::upload Returns Empty Json

### ISSUE THREAD

**Issue by Kent27** [jrm2k6/cloudder#65]
I used the function Cloudder::upload in php and intended to return it and get the url of the image, It responded with the json of an empty api. 
_Note: the image is successfully saved in cloudinary_

<img width="518" alt="capture" src="https://user-images.githubusercontent.com/30821046/52545459-42edf900-2dea-11e9-9b13-a48853b710c8.PNG">

<img width="559" alt="capture2" src="https://user-images.githubusercontent.com/30821046/52545464-57ca8c80-2dea-11e9-931d-2b7834f92413.PNG">

now I know there is a workaround by calling secureShow method, just wanted to make sure if it is possible to return the upload function right away

**Comment by jrm2k6** [comment]
Hi,
You could just do `Cloudder::upload($this->PICTURE_NAME)->getResult();`
