### ISSUE TITLE
secureShow returning scaled image instead of original uri with versioning

### ISSUE THREAD

**Issue by alvintheodora** [jrm2k6/cloudder#66]
Hi,
why does `secureShow()` return '/image/upload/c_fit,h_150,w_150/myImage1.png' instead of '/image/upload/v1550480678/myImage1.jpg'
The second link, I get from opening the cloudinary console directly.
I ran `php artisan vendor:publish --provider="JD\Cloudder\CloudderServiceProvider"` and
I have commented out the scaling in my `config/cloudder.php`, so the returned url is : '/image/upload/myImage1'
So then, how to include the versioning on the returned result?
Thanks

**Comment by alvintheodora** [comment]
@jrm2k6 hello, great libary btw, any ideas?

**Comment by jrm2k6** [comment]
@alvintheodora  Sorry for the delay! Can you provide an easy working snippet reproducing the issue and I can dig in?

**Comment by alvintheodora** [comment]
Hi @jrm2k6 it would be as simple as
`\Cloudder::secureShow('myImage');` returns `"https://res.cloudinary.com/foo/image/upload/myImage"`.
How do we return the versioned one like `https://res.cloudinary.com/foo/image/upload/v1550480678/myImage` 

Reference: [Asset Versions](https://cloudinary.com/documentation/upload_images?query=versioned%20url&c_query=Image%20administration%20%E2%80%BA%20Invalidating%20cached%20media%20assets%20on%20the%20CDN#asset_versions)

**Comment by jrm2k6** [comment]
The easiest way is probably to do this:

```
$res = Cloudder::upload($this->PICTURE_NAME, 'my-kitten')->getResult();
$url = $res['url']
```

Or you can also keep track of the version returned after upload and pass it as part of your options array when calling secureShow:

```
 $res = Cloudder::upload($this->PICTURE_NAME, 'my-kitten')->getResult();
 $version = $res['version'];
 dd(Cloudder::secureShow('my-kitten', ['version' => $version]));
```

**Comment by jrm2k6** [comment]
@alvintheodora Any updates? I will close for now.
