### ISSUE TITLE
Error while uploading video

### ISSUE THREAD

**Issue by andrewaliela** [jrm2k6/cloudder#67]
Hi, I have this package implemented in my Laravel Application (Laravel 5.7.25) and the image upload is working well but the Video upload is not working for me. The following is my image upload code which works perfectly:

    $id = Auth::user()->id;
    $name = $request->input('name');
    $email = $request->input('email');
    $about = $request->input('about');
    $profile_picture = $request->file('profile_picture')->getRealPath();

    Cloudder::upload($profile_picture, null);

    list($width, $height) = getimagesize($profile_picture);

    $image_url = Cloudder::show(Cloudder::getPublicId(), ["width" => $width, "height"=>$height]);

    $data = array('name' => $name,'email' => $email,'about' => $about,'profile_picture' => $image_url);

    User::where('id', $id)->update($data);

    return redirect('/dashboard')->with('response','Profile Updated Succesfully!');

The following is my video upload code which returns the following error: Error in sending request to server - read function returned funny value

        $user_id = Auth::user()->id;
        $video_title = $request->input('video_title');
        $video_description = $request->input('video_description');
        $video_url = $request->file('video_url')->getRealPath();

        Cloudder::uploadVideo($video_url, null);

        $vid_url = Cloudder::show(Cloudder::getPublicId());

        $data = array('user_id' => $user_id, 'video_title' => $video_title, 'video_description' => $video_description, 'video_url' => $vid_url);

        VideoResume::save($data);

        return redirect('/my-video-resumes')->with('response','Profile Published Succesfully!');

Any assistance in figuring out the issue will highly be appreciated. Thanks.

**Comment by jrm2k6** [comment]
@andrewaliela Thanks for the example. I will double check shortly.

**Comment by andrewaliela** [comment]
@jrm2k6 Thank you sir. Looking forward to the assistance.

**Comment by andrewaliela** [comment]
Hi @jrm2k6 any luck with the above?

**Comment by jrm2k6** [comment]
@andrewaliela Sorry I am pretty busy.
I just tried to upload a video with the following:

```
        Cloudder::uploadVideo($this->VIDEO_NAME, null);
        $vid_url = Cloudder::show(Cloudder::getPublicId());
        dd($vid_url);
```
And it works fine for me.

Are you sure the video filename you get is correct?
Can you try to put this file in your public folder: https://github.com/jrm2k6/cloudder-l5-sample-project/blob/master/public/rabbit.mp4

And then run this code:
```
$video_name = public_path('rabbit.mp4');
Cloudder::uploadVideo($video_name, null);
$vid_url = Cloudder::show(Cloudder::getPublicId(), ['resource_type' => 'video', 'format' => 'mp4']);
dd($vid_url);
```

**Comment by andrewaliela** [comment]
Hi @jrm2k6 and thank you for the above response.
I'm going to attempt this and then share the results.

**Comment by andrewaliela** [comment]
Hey @jrm2k6 thank you so much for the assistance, it worked.

Here is my final code:

        $videoresume = new VideoResume;
        $videoresume->user_id = Auth::user()->id;
        $videoresume->video_title = $request->input('video_title');
        $videoresume->video_description = $request->input('video_description');
        
        $video_url = $request->file('video_url')->getRealPath();
        Cloudder::uploadVideo($video_url, null, array('folder' => 'videos'));

        $videoresume->video_url = Cloudder::show(Cloudder::getPublicId(), ['resource_type' => 'video', 'format' => 'mp4']);
        $videoresume->save();
