### ISSUE TITLE
Show method not working for HTTPS

### ISSUE THREAD

**Issue by krisnicolaou** [jrm2k6/cloudder#7]
Hi There,

There seems to be an issue with the show method handling secure URLs. The website has an SSL certificate installed and everything is working, but the images served up by Cloudinary using this package aren't loading with a secure URL. 

I've tried to force the URL within `config/cloudder.php` and also within the `.env` file setting the `CLOUDINARY_BASE_URL` to use HTTPS.

Please let me know if I've missed something.

Thank you,
Kris

**Comment by Migweld** [comment]
Hi Kris,

How are you forcing the HTTPS URL, out of interest? I'm passing a secure key in the scaling array in config/cloudder.php and that makes all Cloudder::show requests use SSL:

```
'scaling'    => array(
        'secure' => true
    )
```

Alternatively, you can pass that key in your options array when performing the cloudder request:

`Cloudder::show($cloudinary_id, array('secure' => true))`

**Comment by krisnicolaou** [comment]
Hey Craig,

Thank you for the reply. I did end up figuring that out, but I thought I wouldn't have to change all instances of the `Cloudder::show(...)` calls. I figured it would be one setting change to make all calls secure.

Everything is working now.

Thanks again,
Kris

**Comment by jrm2k6** [comment]
@krisnicolaou  Oh wow. Sorry I didn't get an email when you opened the issue. Is everything ok now? Or is there something you need still?

@Migweld Thanks for handling this one!

**Comment by krisnicolaou** [comment]
@jrm2k6 no worries, everything is good. I just didn't want to change each instance if there was a single setting. Thanks for following up.

**Comment by joelcuevas** [comment]
I think it would be of value to put this on the readme. Yesterday I spent an hour or so reading code just to understand this... I should have checked the issues first, I know. :P

**Comment by jrm2k6** [comment]
@joelcuevas Will do!

**Comment by jrm2k6** [comment]
Now that I am looking at it, `showPrivateUrl` should give you back a url that has an expiration time so that it is really private. I will add a secureShow method that will serve the pictures through https.
