### ISSUE TITLE
cannot delete pdf,excel file

### ISSUE THREAD

**Issue by ojha007** [jrm2k6/cloudder#74]
unable to delete the pdf  or excel file but  images can be deleted

**Comment by PhPotier** [comment]
I have the same problem with video or audio file. But with image, it's work perfectly

**Comment by PhPotier** [comment]
Maybe you have to add 
`$options = [
'resource_type' = raw
];`  ?
For my problem it was the solution (audio are a ressource type video)

**Comment by Mifayo** [comment]
@PhPotier hello bro,
it works for me i just added
`$options = [ 'resource_type' => 'video ];`
