### ISSUE TITLE
upload url & original size

### ISSUE THREAD

**Issue by X-mac** [jrm2k6/cloudder#77]
Hi there, I'm using cloudder in my laravel project. I can upload the images on cloudinary. 
I use 
  Cloudder::upload($image, $isbn,  array('folder'=>'books');

The file uploaded have png exstension, the original extesion is jpg, and the size is not the original size. ie the url is different:
http://res.cloudinary.com/xxxxx/image/upload/c_fit,h_150,w_150/v1/books/9788807033438.png

there is some settings to do in your pluging? from cloudinary everything is ok

**Comment by dotmarn** [comment]
If you check the cloudder.php file in the config folder you will see the settings there as seen here
`    'scaling'    => [
        'format' => 'png',
        'width'  => 150,
        'height' => 150,
        'crop'   => 'fit',
        'effect' => null
    ],`

**Comment by jrm2k6** [comment]
@X-mac what @dotmarn said is correct! Thanks @dotmarn 
Let me know if it works for you @X-mac and I will close this issue.

**Comment by X-mac** [comment]
thanks dotmarn, I founded the seetings, and change.
