### ISSUE TITLE
How to display all media library from cloudinary 

### ISSUE THREAD

**Issue by silverhand7** [jrm2k6/cloudder#79]
Hi, can you help me how to show entire media library like this from laravel application?

![image](https://user-images.githubusercontent.com/30499443/86691081-166bfa00-c03b-11ea-953f-cdda1ea764f5.png) 

so we display all the media, can cloudder do something like that? 
Thank you in advance..

**Comment by jrm2k6** [comment]
You can definitely use this wrapper to fetch the data from cloudinary.
Where do you store the path to the assets?
What have you tried so far?

**Comment by silverhand7** [comment]
Sorry I'm new here, I don't see on this documentation to show the media entirely. 
I already tried using `curl https://<API_KEY>:<API_SECRET>@api.cloudinary.com/v1_1/<CLOUD_NAME>/resources/image` but only shown 10 media maximum

**Comment by silverhand7** [comment]
I also tried 
![image](https://user-images.githubusercontent.com/30499443/86705893-e75c8500-c048-11ea-8d40-ee96a7313c18.png)
the output 
![image](https://user-images.githubusercontent.com/30499443/86705958-fa6f5500-c048-11ea-9c1a-dbb567e94d3e.png)

**Comment by silverhand7** [comment]
it's fixed by adding 
```
$result = (array) Cloudder::resources([
            'max_results' => 30
         ]);
```
or
```
$result = Cloudder::resources([
            'max_results' => 30
        ]); 

dd($result['resources']); 
```
