### ISSUE TITLE
Must supply api_key

### ISSUE THREAD

**Issue by sil2** [jrm2k6/cloudder#9]
Hi Jeremy,

I'm getting error:
InvalidArgumentException in Cloudinary.php line 648:
Must supply api_key

I have all keys in .inv file and in config/cloudder.php

I go over your file and cannot get how you populate self:config?

maybe the issue is here: 
 public static function reset_config() {
        self::config_from_url(getenv("CLOUDINARY_URL"));
    }
what is CLOUDINARY_URL?  I don't have it.

**Comment by jrm2k6** [comment]
Hi @sil2,

Have you run `php artisan vendor:publish --provider="JD\Cloudder\CloudderServiceProvider"`?

I have an example project at https://github.com/jrm2k6/cloudder-l5-sample-project
The cloudder config file is the following after running the publish command https://github.com/jrm2k6/cloudder-l5-sample-project/blob/master/config/cloudder.php.

Do you have something equivalent?

**Comment by sil2** [comment]
i did run it and the response is :
Publishing complete for tag []!
and my config file

<?php

return array(

```
/*
|--------------------------------------------------------------------------
| Cloudinary API configuration
|--------------------------------------------------------------------------
|
| Before using Cloudinary you need to register and get some detail
| to fill in below, please visit cloudinary.com.
|
*/

'cloudName'  => env('XXXXMYVALUE'),
//'baseUrl'    => env('CLOUDINARY_BASE_URL', 'http://res.cloudinary.com/'.env('dynyxdnng')),
//'secureUrl'  => env('CLOUDINARY_SECURE_URL', 'https://res.cloudinary.com/'.env('dynyxdnng')),
//'apiBaseUrl' => env('CLOUDINARY_API_BASE_URL', 'https://api.cloudinary.com/v1_1/'.env('XXXXMYVALUE')),
'apiKey'     => env('XXXXMYVALUE'),
'apiSecret'  => env('XXXXMYVALUE'),

'scaling'    => array(
    'format' => 'png',
    'width'  => 150,
    'height' => 150,
    'crop'   => 'fit',
    'effect' => null
)
```

);

and sure, XXXXMYVALUE are my keys,

**Comment by jrm2k6** [comment]
I can take a look later today (PT) or tomorrow morning.

I assume you still have the same issue. Can you give me the code you are using in a gist and your full configuration when it comes to cloudder? provider/config/etc

**Comment by jrm2k6** [comment]
Any news on this @sil2 ?

**Comment by sil2** [comment]
hi, Jeremy

It's just magicaly back to work next day. Dont knwo why and wat was the issue. Thank you.  I think, this tread can be just removed.

**Comment by jrm2k6** [comment]
Great, Magic of the Computer World.

**Comment by thuthao541998** [comment]
i have the same problem here but still dont know how to fix it

**Comment by jrm2k6** [comment]
Can you open a new issue to make sure we start fresh?
